### ISSUE TITLE
Wrong and missing translation for german holidays

### ISSUE THREAD

**Issue by Dabbel** [joaomatossilva/DateTimeExtensions#109]
Some translation like second christmas day has the wrong translation and the translation for ascension is missing

**Comment by joaomatossilva** [comment]
Hi, Huge thanks for the fix. Looking forward to Merge it.

Let me think a little bit better regarding if the 2nd Day of Xmas should be on the Christian Holidays or if it should be on the specific class of the Locale.

There are other countries that do observe the same holiday, so putting it on the Christian Holidays might make more sense than the remark I made on the PR

**Comment by joaomatossilva** [comment]
Sorry for the delay (again). So this holiday already exists, and It's called StStephenDay. Maybe add a new translation with the key `StStephenDay` to  `Zweiter Weihnachtsfeiertag` ? at least is what is called on https://en.wikipedia.org/wiki/Public_holidays_in_Germany

**Comment by Dabbel** [comment]
I think you are referencing the table under "Public holidays in the former German Democratic Republic", these are outdated. The correct table is under "List by state".

**Comment by joaomatossilva** [comment]
I'm a bit reluntant to add yet another holiday to the same day with similar (if not the same) celebration as Boxing Day (that is under the Global Holidays) or the St StephenDay (that is under the Christian Holidays).

If you really think it is "more rightfull" to add yet another holiday, please add it ontly on the DE_DEHolidayStrategy please.

is that a good compromise?

**Comment by Dabbel** [comment]
Changed a bit on my branch, think is fits both of us the best

**Comment by joaomatossilva** [comment]
Merged!

**Comment by joaomatossilva** [comment]
Oh.. and Thank you very much, also sorry about the delay 😛
