### ISSUE TITLE
Liberation Day in Netherlands

### ISSUE THREAD

**Issue by sergiu05** [joaomatossilva/DateTimeExtensions#111]
Hi,

Could you review the implemented rule for _Liberation Day_ - _Netherlands_? According with wikipedia and the official government site, the _Liberation Day_ is celebrated every year since 1990, and every five years between 1945 and 1989:

    https://www.government.nl/topics/working-hours/question-and-answer/public-holidays-in-the-netherlands
    https://en.wikipedia.org/wiki/Liberation_Day_(Netherlands)

**Comment by joaomatossilva** [comment]
Hi, yes, I'll have a look at it

**Comment by joaomatossilva** [comment]
Fixed, should be releases as soon it builds
