### ISSUE TITLE
Juneteenth - new US Holiday as of 2021 6/19/2021

### ISSUE THREAD

**Issue by rdepin** [joaomatossilva/DateTimeExtensions#112]
Added Juneteenth to US Holiday Strategy though couldn't push change.

        //Juneteenth - new as of 2021
        private static Holiday juneteenth;
        public static Holiday Juneteenth
        {
            get
            {
                if (juneteenth == null)
                {
                    juneteenth = new YearDependantHoliday(year => year >= 2021, new FixedHoliday("Juneteenth", 6, 19));
                }
                return juneteenth;
            }
        }

**Comment by joaomatossilva** [comment]
I'm more that ok accepting this contribution, but I find that wierd that you can't push the change.

Is this of any help? https://docs.github.com/en/get-started/using-git/pushing-commits-to-a-remote-repository

You should "fork" this repository to your own account, and only then clone it. This will allow you to push your comits (that should be done on a branch that you create) and then you will be able to open a MR to this repository.

Try to see if you can find a solution for it, so it can be connected to your username on the repository history. There is plenty of documentation around on how to contribut to open source projected. If you still don't manage to do it, give me a ping

**Comment by rdepin** [comment]
Thanks, It might be how Git works in VS – I’ll read the doc you sent.  To be honest I’ve had a love/hate relation with Git.  Great Library by the way.

**Comment by JonahGregory** [comment]
Is this in progress? We could use this new holiday too. I'm happy to make the PR to get it out of limbo.

**Comment by joaomatossilva** [comment]
I'll be happy to accept it too 👍

**Comment by JonahGregory** [comment]
Made PR #113

**Comment by joaomatossilva** [comment]
Merged

**Comment by joaomatossilva** [comment]
Should be released soon under 5.5.3
