### ISSUE TITLE
Fetching holiday lists for en-ZA is broken

### ISSUE THREAD

**Issue by tanmoy-purkait** [joaomatossilva/DateTimeExtensions#115]
Fetching the lists for en-ZA is broken and throws an `An item with the same key has already been added.` error.

For reference,

http://datetimeextensions.azurewebsites.net/en-ZA/Calendar/Index/2022

<img width="1792" alt="Screen Shot 2022-04-29 at 10 00 32 AM" src="https://user-images.githubusercontent.com/88004679/165959446-aeb0399b-cc14-4747-9e82-7b8c60372011.png">

Will it be possible to put in a quick fix for this? Thanks in advance!

**Comment by joaomatossilva** [comment]
Hi, are you experiencing the error on the library or just the sample site?

Asking this because I think this was already fixed on https://github.com/joaomatossilva/DateTimeExtensions/pull/114 version 5.5.4 of the lib.

The sample might not be running the latest version of the lib

**Comment by tanmoy-purkait** [comment]
Yes, that was the issue. The Library version was set to 5.5.0. Updating to 5.5.4 fixed it. Thanks!
