### ISSUE TITLE
Holidays FR

### ISSUE THREAD

**Issue by bartbc** [joaomatossilva/DateTimeExtensions#120]
Hi, thanks for your DateTimeExttensions!
It's useful and it works really well.

On the other hand, Whit Monday (06/06/2022, 29/05/2023 for example) is missing for the AllYearHolidays() function

Thanks in advance

**Comment by joaomatossilva** [comment]
Hi, yes, I've reviewed the FR holidays, and there were some missing. thanks.

Should be fixed in 5.5.8
