### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [joaomatossilva/DateTimeExtensions#128]
Maybe You will be interested in hosting API Explorer online: 
[www.robiniadocs.com/d/datetimeex](https://www.robiniadocs.com/d/datetimeex/api/DateTimeExtensions.TimeExtensions.html)

**Comment by joaomatossilva** [comment]
Thanks, Looks good

**Comment by joaomatossilva** [comment]
you might want to omit the "www" part, since it's giving some SSL issues cause the certificate does not have that part of the domain.
