### ISSUE TITLE
DateTime for the region Kenya

### ISSUE THREAD

**Issue by ReaganNet** [joaomatossilva/DateTimeExtensions#129]
using System;

class Program
{
    static void Main()
    {
        // Specify the time zone for Kenya (East Africa Time)
        TimeZoneInfo kenyaTimeZone = TimeZoneInfo.FindSystemTimeZoneById("E. Africa Standard Time");

        // Get the current UTC time
        DateTime utcNow = DateTime.UtcNow;

        // Convert UTC time to Kenya local time
        DateTime kenyaLocalTime = TimeZoneInfo.ConvertTimeFromUtc(utcNow, kenyaTimeZone);

        Console.WriteLine("UTC Time: " + utcNow);
        Console.WriteLine("Kenya Local Time: " + kenyaLocalTime);

        Console.ReadLine();
    }
}

**Comment by Bellamalwa** [comment]
The output format is clear and informative with "UTC Time" and "Kenya Local Time.

**Comment by onyangoju** [comment]
i think this is it

**Comment by joaomatossilva** [comment]
Not understand what this has to do with this library. There are a lot information out there how to handle timezones. You may also want to take a look ad NodaTime project that is specialized on that.
