### ISSUE TITLE
IndianHolidays

### ISSUE THREAD

**Issue by AnirudhG07** [joaomatossilva/DateTimeExtensions#146]
As mentioned in PR #145 (now closed) I would like some help to add Indian Holidays into this extensions. As mentioned the indian Holiday system works on Hindu Calender which means, the dates vary every year except important Government Holidays which are fixed. <br>
If this is a system I can add the Hindu Calendar Holidays (all Indian Holidays), please share with me @joaomatossilva and also some code to use for reference, with guidelines.<br> It would be great if we could add an Extension for holidays which vary every year, like in India, and i am sure many Asian countries will have similar systems for some of their holidays.

**Comment by joaomatossilva** [comment]
You can see already on the Chinese strategy that it's using a non-gregorian calendar. 
The library uses the concept of Day and Months but always associated to a [Calendar](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.calendar?view=net-8.0). This means that if exists an Hindu Calendar it is possible to represent an holiday

**Comment by AnirudhG07** [comment]
Yes I saw the Chinese one. I will see how I can add to it. Thank you.

**Comment by joaomatossilva** [comment]
is it the most approximate calendar this one? https://learn.microsoft.com/en-us/dotnet/api/system.globalization.eastasianlunisolarcalendar?view=net-8.0

**Comment by AnirudhG07** [comment]
Yes actually. Even Chinese is also I think lunisolar. It is similar. it is dependant on moon and astronomical object positioning.
So I think only the event dates are different rest are similar.

**Comment by CoderAmbar** [comment]
`using System;
using System.Collections.Generic;
using System.Linq;

namespace DateTimeExtensions.Holidays.India
{
    public class IndianHolidaysProvider
    {
        // Main method to retrieve all holidays for a given year
        public IEnumerable<DateTime> GetHolidays(int year)
        {
            var holidays = new List<DateTime>();

            // Add fixed-date holidays
            holidays.Add(new DateTime(year, 1, 26));  // Republic Day
            holidays.Add(new DateTime(year, 8, 15));  // Independence Day
            holidays.Add(new DateTime(year, 10, 2));  // Gandhi Jayanti

            // Add variable holidays using helper methods
            holidays.Add(GetDiwaliDate(year));  // Diwali
            holidays.Add(GetHoliDate(year));    // Holi

            return holidays;
        }

        // Checks if a given date is a holiday by seeing if it’s in the list
        public bool IsHoliday(DateTime date)
        {
            return GetHolidays(date.Year).Contains(date);
        }

        // Placeholder for Diwali date calculation
        private DateTime GetDiwaliDate(int year)
        {
            // NOTE: In a real implementation, calculate Diwali based on the Hindu calendar
            return new DateTime(year, 11, 4); // Placeholder
        }

        // Placeholder for Holi date calculation
        private DateTime GetHoliDate(int year)
        {
            // NOTE: Calculate Holi based on Phalguna Purnima in Hindu calendar
            return new DateTime(year, 3, 9); // Placeholder
        }
    }
}
`

**Comment by CoderAmbar** [comment]
Here is the solution:
`using System;
using System.Collections.Generic;
using System.Linq;

namespace DateTimeExtensions.Holidays.India
{
    public class IndianHolidaysProvider
    {
        // Main method to retrieve all holidays for a given year
        public IEnumerable<DateTime> GetHolidays(int year)
        {
            var holidays = new List<DateTime>();

            // Add fixed-date holidays
            holidays.Add(new DateTime(year, 1, 26));  // Republic Day
            holidays.Add(new DateTime(year, 8, 15));  // Independence Day
            holidays.Add(new DateTime(year, 10, 2));  // Gandhi Jayanti

            // Add variable holidays using helper methods
            holidays.Add(GetDiwaliDate(year));  // Diwali
            holidays.Add(GetHoliDate(year));    // Holi

            return holidays;
        }

        // Checks if a given date is a holiday by seeing if it’s in the list
        public bool IsHoliday(DateTime date)
        {
            return GetHolidays(date.Year).Contains(date);
        }

        // Placeholder for Diwali date calculation
        private DateTime GetDiwaliDate(int year)
        {
            // NOTE: In a real implementation, calculate Diwali based on the Hindu calendar
            return new DateTime(year, 11, 4); // Placeholder
        }

        // Placeholder for Holi date calculation
        private DateTime GetHoliDate(int year)
        {
            // NOTE: Calculate Holi based on Phalguna Purnima in Hindu calendar
            return new DateTime(year, 3, 9); // Placeholder
        }
    }
}
`
