### ISSUE TITLE
[Question] What is the function of  BuildObservancesMap() method in the code

### ISSUE THREAD

**Issue by sami-daniel** [joaomatossilva/DateTimeExtensions#161]
Basically that. I saw this method and wanted to know what it does, if it is really useful... I couldn't identify its function

![image](https://github.com/joaomatossilva/DateTimeExtensions/assets/130937402/35f51e86-3b99-4f5f-bc14-bb1cf18ddc54)

**Comment by joaomatossilva** [comment]
It projects the Holidays dictionary (that has the rules to calculate the holidays of any given year) to resolve the day of each holiday (excluding duplicates) for a given year.

**Comment by sami-daniel** [comment]
So is it used to calculate rolling holidays? And another question, why is it a virtual method

**Comment by joaomatossilva** [comment]
There are cultures where a day might be oberserved on a different day, like for example en-US when a oliday falls on a weekend

**Comment by sami-daniel** [comment]
Does the base method already calculate this or do I need to redo the calculations? Why did I see that the method is defined as virtual

**Comment by sami-daniel** [comment]
> Does the base method already calculate this or do I need to redo the calculations? Why did I see that the method is defined as virtual

So in this I can declare common holidays and just implement the method

**Comment by joaomatossilva** [comment]
unless there's anything particular that deviates from the standard observation, there shouldn't be any reason to implement the method.

Ideally the all the Holidays should be declared on the InnerDictionary, so they can be listed, even if not resolved for a given year

**Comment by sami-daniel** [comment]
Ahhhhhh. Now I get it. Before, I was thinking that I only added fixed holidays to the Inner Dictionary. Thx you. I'm going to make some changes
