### ISSUE TITLE
set time extension method possibly redundant / improperly named

### ISSUE THREAD

**Issue by catthegirl** [joaomatossilva/DateTimeExtensions#164]
As the method is currently implemented unless there is some hidden logic that I'm not seeing all it does is return the output of the add time method with the same args as if you were to call the method directly. As well the name set time seems misleading for a function that only adds time. Sorry for the bad formatting I'm very new to GitHub and c# is not my strongest language so I'm very sorry if there is something I'm missing

**Comment by catthegirl** [comment]
Thank you for the explanation I completely overlooked the dateTime.date although I would like to ask one more question. Why not get rid of the middle man and directly create a new datetime object with the desired time rather than relying on the add time method and the date property

**Comment by joaomatossilva** [comment]
That's one solution. In terms of code reusability, this makes more sense.

In any way, if you think/prove that doing it in other way is better, more performant, etc, feel free to submit a Pull Request with the change ;)
