### ISSUE TITLE
WebsiteNotSecure

### ISSUE THREAD

**Issue by pranavinsight** [joaomatossilva/DateTimeExtensions#169]
Your Website is not secure and it keeps warning me not to go to that website... and Firstly, Why i need to download the .zip anyway? Please try to improve and change your website to look more clean and modern. and try to get the "https" address and an SSL certificate. Then only people believe you and you will be a rich guy. So, please get an SSL certificate and customize the website a bit modern. You can even use javascript to enhance the experience(sorry if i am wrong in any of these points).

**Comment by joaomatossilva** [comment]
What website?

**Comment by zeusssz** [comment]
i dont think that they have a website. its possible you went to a fake website which contains malicious code.

**Comment by 1am-programmer** [comment]
It is not secure.

**Comment by joaomatossilva** [comment]
but what is not secure? http://www.kspace.pt/DateTimeExtensions/ ? the site now redirects to https, and it was the DNS that was still pointing to old A records from github, not a certificate issue.

**Comment by Hex4dec** [comment]
> Please try to improve and change your website to look more clean and modern

https://pranavinsight.github.io/fivestarcoffeemakers/About%20OUR%20coffee.html

what

**Comment by pranavinsight** [comment]
Oh, that one right? It was my first website.... Pardon me pls

**Comment by pranavinsight** [comment]
btw, that reaction was very funny 🤣🤣🤣🤣🤣
But, Mister Hex4Dec, i will surely make a lot cooler theme in my future projects. Glad to see you Mister Hex4Dec. 👍

**Comment by zeusssz** [comment]
> Oh, that one right? It was my first website.... Pardon me pls

brother. you cant talk shit about other peoples websites (while they dont have one 💀), when yours looks like its been made in 5 minutes.

**Comment by joaomatossilva** [comment]
Closing this issue since It's not developing to be related to this project.

Let's try to be inclusive and helpful on the open source community. Everyone has his own glass rooftops.
