### ISSUE TITLE
Adding Kenya Calendar

### ISSUE THREAD

**Issue by RafaelJohn9** [joaomatossilva/DateTimeExtensions#177]
I would like to add a Kenyan calendar. In this repository.

**Comment by joaomatossilva** [comment]
You don't need to ask for permission. Just create a PR ;)

**Comment by hyman233** [comment]
The B
________________________________

**Comment by RafaelJohn9** [comment]
@joaomatossilva thanks then I'll get working on it

**Comment by hyman233** [comment]
let me know exactly what you're gonna do.
________________________________
