### ISSUE TITLE
Proposal: Add Moroccan Holidays and Working Days to the Holiday Data

### ISSUE THREAD

**Issue by grichali** [joaomatossilva/DateTimeExtensions#191]
Hi, hope you're doing well!

I am interested in contributing to the project by adding Moroccan public holidays and working days to the holiday data. Currently, the holiday data does not include holidays and working days specific to Morocco.

I plan to include these changes holiday data structure. If there are any specific formats, guidelines, or additional requirements I should follow, please let me know.

I’d appreciate information on any contributing guidelines or standards I should follow, the recommended steps for submitting these changes (such as creating a new branch and testing), and any available documentation or resources that could assist with this contribution.

**Comment by joaomatossilva** [comment]
Just create a PR and look at current implementations
