### ISSUE TITLE
en-AU - Queen's birthday. State differences.

### ISSUE THREAD

**Issue by ashleybroughton** [joaomatossilva/DateTimeExtensions#65]
The Queen's birthday in the en-AU strategy has been implemented to be the 2nd Monday in June. This is applicable across most states, however there are exceptions.  
  
How would these be accounted for?

Location | 2017
---|---
Australian Capital Territory | Monday 12th June
New South Wales | Monday 12th June
Northern Territory | Monday 12th June
South Australia | Monday 12th June
Tasmania | Monday 12th June
Victoria | Monday 12th June
Western Australia | Monday 25th September
Regional WA - Port Hedland | Monday 7th August
Regional WA - Karratha | Monday 7th August
Regional WA - Marble Bar | Monday 3rd July
Regional WA - Newman | Monday 21st August
Queensland | Monday 2nd October

https://github.com/joaomatossilva/DateTimeExtensions/blob/c2cf55ca35c30f23bc39f2b2259563fa009ba8e3/src/DateTimeExtensions/WorkingDays/CultureStrategies/EN_AUHolidayStrategy.cs#L136-L150  
  
https://www.fairwork.gov.au/leave/public-holidays/list-of-public-holidays  
  
https://www.commerce.wa.gov.au/labour-relations/regional-dates-queens-birthday-public-holiday

**Comment by joaomatossilva** [comment]
Hi,

Since regions are not yet supported, I guess the we aim for the most common one, that will be on the 2nd Monday in June.

Regions is something I do want to introduce in the future.

**Comment by joaomatossilva** [comment]
@ashleybroughton Well, I've been looking at this, and while regions are now supported on 5.0, the problem with those regions is that their dates are set yearly by their governanors.

This means I can't really do much. Maybe setting them individually based on year, but this would be inaccurate.

I think this is one of the cases where this tool can't help on 100%. but if this is really a need for you, you can always extend it and support all the edge cases you see fit.

**Comment by ashleybroughton** [comment]
It might not be desired to use such a source, but the complete list of holidays is published by the Australian government in XML format. Perhaps this could be worked in some how.  
http://www.australia.gov.au/about-australia/special-dates-and-events/public-holidays/xml
