### ISSUE TITLE
Holiday falls on weekend

### ISSUE THREAD

**Issue by waynebrantley** [joaomatossilva/DateTimeExtensions#70]
Does this have support for if the holiday falls on a weekend?
I scanned some of the source and did not notice it.

So for example if Christmas falls on a Saturday, the actual work holiday day is the Friday before Christmas.  Similarly if it falls on Sunday the work holiday is the following Monday.  

This is true for all fixed holidays.  When you add 5 business days and it lands on the Friday that is not the actual holiday but is the Friday before the actual holiday (or Monday if appropriate) it needs to skip it and go to the next business day.

**Comment by joaomatossilva** [comment]
Hi.. that behaviour does depend on the actual culture you're checking... 

The portuguese for example, if an holiday falls on a weekend, then it's not observed on the next (or previous working day).

On the United States for example, if an holiday falls on a Saturday it's observed on the previous Friday, or if it falls on a Sunday it's observed on the next Monday.

**Comment by waynebrantley** [comment]
Great - so you are saying it already takes care of this?

**Comment by joaomatossilva** [comment]
Oh god.. only today I actually noticed I haven't replied to this.
Yes, it does take care of it. It actually depends on the culture implementation.
