### ISSUE TITLE
Business days do not take time into account

### ISSUE THREAD

**Issue by waynebrantley** [joaomatossilva/DateTimeExtensions#71]
If it is Monday at 2pm and you add 2 business days to that, it would be Wednesday of course.
However, if your business closes at 1pm every day, 2 business days after 2pm would actually be Thursday!

So, adding business days really needs an optional cutoff time.

**Comment by joaomatossilva** [comment]
No indeed, adding working days do not take time into consideration...
I guess that would be a nice addition

**Comment by waynebrantley** [comment]
I have this sort of functionality currently but was looking to see if I could use your library, that is why I mentioned this feature.  Other than that..nice work.
