### ISSUE TITLE
Christmas Eve missing from SV_SEHolidayStrategy.cs

### ISSUE THREAD

**Issue by rasmusoh** [joaomatossilva/DateTimeExtensions#90]
Christmas Eve seem to be missing from the working day calculation for sv-SE culture.

see for example:
https://www.riksbank.se/en-gb/press-and-published/calendar/bank-holidays-2019/
https://www.nordea.com/sv/om-nordea/kontakt/helgdagar/
https://www.officeholidays.com/countries/sweden/index.php
https://en.wikipedia.org/wiki/Public_holidays_in_Sweden -> listed under De-facto public holidays

**Comment by rasmusoh** [comment]
New Years Eve is also missing!

**Comment by joaomatossilva** [comment]
Thank you for the feedback. I'll look into this very soon

**Comment by joaomatossilva** [comment]
should be fixed on version 5.4.1
